### ISSUE TITLE
Rename variables under priceSpecification

### ISSUE THREAD

**Issue by BigDataKatha** [EveryMundo/emDataStandards#17]
**Current variable names:**
````
{
  "@type": "PriceSpecification",
  "description": "JOURNEY",
  "price": 234.21,
  "totalPrice": 250.6,
  "totalPriceUSD": 250.6,
  "taxPrice": 16.39,
  "fuelPrice": 57.89,
  "additionalFeesPrice": 12,
  "currency": "USD",
  "currencySymbol": "$",
  "priceMarketId": "USD-US",
  "isSoldOut": false,
  "lastUpdatePriceTime": "2018-02-12T16:49"
}
````

**Issues:**

- Not every country needs to display taxes on the Flights Results Page. Also, not every airModule displays fares with taxes. For tracking scalability, I need one variable that I can consistently refer to that may or may not include taxes.
- Under fareTensor, we may not have the price without taxes. Therefore, we should use another variable.

 **Suggestions:**

- For FareNet, include fuel price under additionalFeesPrice if listed separately. Maintain fuelPrice variable under priceSpecification if needed to specify in the future.
- Rename price to **priceNoFees** to be more descriptive in the variable name
Rename taxPrice to **taxAmount** for more clarity
- Add new variable **priceAdvertised** that we can refer to for module tracking

Note: totalPrice = priceNoFees + taxAmount + additionalFeesPrice

{
  "@type": "PriceSpecification",
  "description": "JOURNEY",
  "priceNoFees": 234.21,
  "totalPrice": 250.6,
  "totalPriceUSD": 250.6,
  "taxAmount": 16.39,
  "fuelPrice": 57.89,
  "additionalFeesPrice": 12,
  "priceAdvertised": 110,
  "currency": "USD",
  "currencySymbol": "$",
  "priceMarketId": "USD-US",
  "isSoldOut": false,
  "lastUpdatePriceTime": "2018-02-12T16:49"
}
````

@danielsan @yartiles @darielnoel @howardem @neilgoldman @renecairo

**Comment by danielsan** [comment]
If we rename the **taxPrice** to **taxAmount** we should also rename **additionalFeesPrice** to **additionalFeesAmount**

**Comment by neilgoldman** [comment]
+1 Daniel's comment.

I think `priceBeforeTaxesAndFees` is more explicit than `priceNoFees`, but I also understand if most people think that is too verbose so either is fine with me.

**Comment by danielsan** [comment]
+1 @neilgoldman

**Comment by anahiem** [comment]
Hi guys,

What about "priceMarketId" field, to me is a little misleading by reading the values, what about "currencyMarketId"?

**Comment by neilgoldman** [comment]
@anahiem I don't think currency is correct because sometimes it's more than just a currency or not a currency at all. But I agree we can probably get a more clear name.

90% of the time or more it will just be the currency code, or currency code + a market code (like some airlines sell USD to USA and some South American countries, but the prices are not compatible. So "USD-us" and "USD-sa" (sa=south-america) or something.)

The only instance I can think of that isn't based on currency is one airline who separate by the ATHA and LONA point-of-sale, but there's probably more. And then another is completely point-of-origin based, so it's technically not currency based, but that system also "solves itself" and can't have conflicts, so I don't know how we actually label those (or if we even label them).

However, I don't think we do any of this on the Farenet side? If we have this field here we need to make sure it's meaningful. If it doesn't correctly match the pricing market groups ID, it can be harmful because we will either incorrectly split up pricing, or we will incorrectly combine prices that should not be.

Maybe something just like `marketId` ? I know this is a term we've tried to find a better definition of for a long time. What's the best name to define "groups of pricing that may be combined within themselves but not outside themselves". Market works, but also is sometimes confused with the site-edition when speaking about that.

**Comment by danielsan** [comment]
Suggestions:
- marketGroup
- pricingGroup
- pricingMarketId
- pricingMarketGroup

**Comment by BigDataKatha** [comment]
@neilgoldman, @danielsan , @anahiem 

I suggest **pricingGroupId**.

Sometimes the variable in question can contain currency, sometimes not. What would the variable output be, for example?
Sometimes the variable contains one country code, sometimes a region or market group? Usually region codes are also capitalized. (See: [Geography Nomenclature](https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_(data_file))) How do we know the difference between the continent and country code "SA" South America vs. South Africa, respectively?

**Comment by neilgoldman** [comment]
> How do we know the difference between the continent and country code "SA" South America vs. South Africa, respectively?

Well the airline that prices USD separately for USA and South America doesn't fly to South Africa ;P 

Jokes aside, that's a very good point. And sometimes in cases like that, the airline themselves tend to not even know their exact pricing groups and we have to figure it out. The "USD-us" and "USD-sa" is how I've solved that one case on my end but that's not the airline's official designation, I don't believe they have an official way of identifying the difference between those pricing groups.

"ATHA308AA" and "LONA308AA" is the only real example of a non-currency ID which is actually assigned by the airline.

"USD-us" and "USD-sa" could just as easily be "USD-1" and "USD-2", or "1" and "2", or "USD-USA" and "USD-SOUTH-AMERICA" or etc. As long as the strings are separate.

We can keep a private list in Confluence of all the identifiers they use and what they mean. Or do you think we should work out a standardized way to do it. My only worry about that is these edge cases may be too unique to create a standard for.

**Comment by BigDataKatha** [comment]
@neilgoldman , I think in that case we should not standardize it for now. What do @danielsan and @anahiem think?

**Comment by BigDataKatha** [comment]
Current proposal:

````
{
"@type": "PriceSpecification",
"description": "JOURNEY",
"priceBeforeTaxesAndFees": 234.21,
"totalPrice": 250.6,
"totalPriceUSD": 250.6,
"taxAmount": 16.39,
"fuelPrice": 0,
"additionalFeesAmount": 0,
"priceAdvertised": 250.6,
"currency": "USD",
"currencySymbol": "$",
"pricingGroupId": "USD-US",
"isSoldOut": false,
"lastUpdatePriceTime": "2018-02-12T16:49"
}
````

**Comment by BigDataKatha** [comment]
Final specification:

````
{
"@type": "PriceSpecification",
"description": "JOURNEY",
"priceBeforeTaxesAndFees": 234.21,
"totalPrice": 250.6,
"totalPriceUSD": 250.6,
"taxAmount": 16.39,
"fuelPrice": 0,
"additionalFeesAmount": 0,
"advertisedPrice": 250.6,
"currencyCode": "USD",
"currencySymbol": "$",
"pricingGroupId": "USD-US",
"isSoldOut": false
}
````

**Comment by BigDataKatha** [comment]
Updated: https://everymundo.github.io/emDataStandards/documentation/build/#pricespecification
