### ISSUE TITLE
specifications under adwords.schema.json 

### ISSUE THREAD

**Issue by anahiem** [EveryMundo/emDataStandards#19]
Hi @BigDataKatha 

As I just saw that we have an Adwords.schema.json

I'm wondering if we should add more fields under it like business feeds data or should we create specific schemas by AdWords objects.

I could work on some examples, let me know.

**Comment by BigDataKatha** [comment]
Hi @anahiem,

I think we should create specific schemas by AdWords object, so that we can maybe use them outside of AdWords. We created this specific schema having the campaign naming convention decoding table in mind. But I think it's a good idea to add the schemas you mentioned, so we can ensure consistency in PM. Can I close this issue? :)

Kat

@unoriginalbanter
